# Site settings
title: 龙之叶博客
email: longzhiye163@163.com
description: 龙之叶博客
# footer_text: 'Made with <span class="icon-favorite pulse"></span> by <a href="http://joshuaraichur.com">Joshua Raichur</a>. <a href="http://github.com/raichur/material-jekyll">Fork the source.</a>'
footer_text: '<span class="icon-favorite pulse"></span>龙之叶版权所有'
baseurl: ""

# Social usernames
# twitter_username: JoshuaRaichur
github_username:  longzhiye
# dribbble_username: geek
# instagram_username: xpl.ore
email: longzhiye163@163.com

# Build settings
markdown: kramdown
include: ['_pages', '_assets']
exculde: ['.sass_cache', 'README.md']
sass:
  sass_dir: '_assets/_sass'
permalink: "/:title/"

# Defaults
defaults:
  -
    scope:
      path: "_pages"
    values:
      is_in_nav: true
